### ISSUE TITLE
Windows yarn vite Command failed

### ISSUE THREAD

**Issue by michalhudecek** [IndexXuan/vue-cli-plugin-vite#1]
Hi,

I am getting command failed when trying to run `npm run vite` in my vue project. Am I missing any prerequisities?

```
npm ERR! code 1
npm ERR! path C:\Users\user\Documents\project
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./bin/vite
```

I only ran `vue add vite`. I can see these 3 files were changed:

![image](https://user-images.githubusercontent.com/1215304/108592916-bda26500-7370-11eb-92f4-704959ce07a8.png)

Is there anything else that needs to be done?

I have 
- @vue/cli 4.2.3
- Latest Windows 10
- node v12.20.0

**Comment by IndexXuan** [comment]
@michalhudecek I dont have Windows PC. try to rename bin/vite to bin/vite.js？It is just node to exec file. No extra errors？

**Comment by michalhudecek** [comment]
@IndexXuan No extra errors. Renaming didn't help.

However, I managed to launch `yarn vite` in WSL on Windows (Ubuntu 20.04.1 LTS). However, the website doesn't load due to following errors. Any idea where to look?

![image](https://user-images.githubusercontent.com/1215304/108594170-9f406780-7378-11eb-84a7-c0ae86e70b00.png)

FYI ... running `yarn serve` which uses `vue-cli` works. The webiste loads just fine.

**Comment by IndexXuan** [comment]
@michalhudecek 
vite serve by folder structure. maybe alias or something, how you import it ?

**Comment by michalhudecek** [comment]
@IndexXuan I am not sure what you mean.

**Comment by IndexXuan** [comment]
@michalhudecek import vue should with .vue ext.

**Comment by michalhudecek** [comment]
You mean in main.js?

![image](https://user-images.githubusercontent.com/1215304/108594662-9c934180-737b-11eb-97e5-ad1167c35c20.png)

**Comment by IndexXuan** [comment]
@michalhudecek In where you import Footer.vue, vite required .vue ext

**Comment by michalhudecek** [comment]
I see. Perfect! Works like a charm. It is working for me now. Should I close this issue?

The original taks was for making it work on Windows itself but WSL is fine with me.

**Comment by IndexXuan** [comment]
@michalhudecek help find the problem will be better, maybe delete first line in bin/vite?

**Comment by michalhudecek** [comment]
> @michalhudecek help find the problem will be better, maybe delete first line in bin/vite?

That didn't help. I managed to get more detailed error though:

```
PS C:\Users\user\Documents\signalizator-homepage>  npm run vite

> signalizator-homepage@0.1.0 vite C:\Users\user\Documents\signalizator-homepage
> node ./bin/vite

running: vite --config C:\Users\user\Documents\signalizator-homepage\node_modules\vue-cli-plugin-vite\config\index.ts
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn vite ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn vite',
  path: 'vite',
  spawnargs: [
    '--config',
    'C:\\Users\\user\\Documents\\signalizator-homepage\\node_modules\\vue-cli-plugin-vite\\config\\index.ts'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! signalizator-homepage@0.1.0 vite: `node ./bin/vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the signalizator-homepage@0.1.0 vite script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-02-20T12_33_21_960Z-debug.log
```

**Comment by michalhudecek** [comment]
Here is an additional error log in case it helps:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'vite'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.20.0
4 verbose run-script [ 'previte', 'vite', 'postvite' ]
5 info lifecycle signalizator-homepage@0.1.0~previte: signalizator-homepage@0.1.0
6 info lifecycle signalizator-homepage@0.1.0~vite: signalizator-homepage@0.1.0
7 verbose lifecycle signalizator-homepage@0.1.0~vite: unsafe-perm in lifecycle true
8 verbose lifecycle signalizator-homepage@0.1.0~vite: PATH: C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\user\Documents\signalizator-homepage\node_modules\.bin;C:\Program Files\PowerShell\7;C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\php;C:\ProgramData\ComposerSetup\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\7-preview\preview;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7\;C:\Ruby26-x64\bin;C:\Ruby27-x64\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\user\AppData\Roaming\Composer\vendor\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin;;C:\Users\user\AppData\Local\Programs\Python\Python38;C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\user\AppData\Roaming\npm
9 verbose lifecycle signalizator-homepage@0.1.0~vite: CWD: C:\Users\user\Documents\signalizator-homepage
10 silly lifecycle signalizator-homepage@0.1.0~vite: Args: [ '/d /s /c', 'node ./bin/vite' ]
11 silly lifecycle signalizator-homepage@0.1.0~vite: Returned: code: 1  signal: null
12 info lifecycle signalizator-homepage@0.1.0~vite: Failed to exec vite script
13 verbose stack Error: signalizator-homepage@0.1.0 vite: `node ./bin/vite`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid signalizator-homepage@0.1.0
15 verbose cwd C:\Users\user\Documents\signalizator-homepage
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "vite"
18 verbose node v12.20.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error signalizator-homepage@0.1.0 vite: `node ./bin/vite`
22 error Exit status 1
23 error Failed at the signalizator-homepage@0.1.0 vite script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ufologist** [comment]
try edit `./bin/vite`

`const serveService = spawn('vite', params, { cwd, stdio: 'inherit' })`
=>
`const serveService = spawn('vite', params, { cwd, stdio: 'inherit', shell: process.platform === 'win32' })`

[SPAWN NPM ENOENT](https://www.cnblogs.com/tylz/p/12060980.html)

**Comment by michalhudecek** [comment]
Yes, it helps! All working now :)

**Comment by IndexXuan** [comment]
@ufologist @michalhudecek you are my hero, will be fix and release soon.
