### ISSUE TITLE
runtimeCompiler option seems to be ignored

### ISSUE THREAD

**Issue by mickeyvip** [IndexXuan/vue-cli-plugin-vite#10]
Hello and thank you for the plugin.

I am trying to set my current project to work with it.

There is a 3rd party package in my project that requires a runtime compiler, so in `vue.config.js` the setting is:

```js
runtimeCompiler: true,
```

But it seems not be taken into account a runtime exception is thrown:

```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. 
  Either pre-compile the templates into render functions, or use the compiler-included build.
```

Should I set it in some other way?

Thank you.

**Comment by a20185** [comment]
@mickeyvip If template configuration is needed, setting [vueTemplateOptions in vitePluginVue2Options](https://github.com/underfin/vite-plugin-vue2/blob/master/src/index.ts#L26) in [PluginOptions Field](https://github.com/IndexXuan/vue-cli-plugin-vite#Options) may help.

**Comment by IndexXuan** [comment]
@mickeyvip never use this option before. I will figure it out. IMO it is just alias for vue/dist/vue.xxx.js. Not hard to impl.

**Comment by IndexXuan** [comment]
@mickeyvip  support in v0.2.1, please upgrade.

**Comment by mickeyvip** [comment]
Thank you!

**Comment by mickeyvip** [comment]
Sorry, but the latest NPM version seems to be `0.2.0`

**Comment by mickeyvip** [comment]
I tried
```
$ npm i -D vue-cli-plugin-vite@0.2
```

this installed `0.2.0` version, but when running the `dev` it throws an exception:

```
> export MODE=development && node ./bin/vite

running: vite --config /Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vue-cli-plugin-vite/config/index.ts
failed to load config from /Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vue-cli-plugin-vite/config/index.ts
error when starting dev server:
TypeError: vueConfig.chainWebpack is not a function
    at Object.<anonymous> (/Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vue-cli-plugin-vite/config/index.ts:36:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.require.extensions.<computed> [as .ts] (/Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vite/dist/node/chunks/dep-d13406fa.js:48450:20)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadConfigFromBundledFile (/Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vite/dist/node/chunks/dep-d13406fa.js:48458:17)
    at loadConfigFromFile (/Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vite/dist/node/chunks/dep-d13406fa.js:48394:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async resolveConfig (/Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vite/dist/node/chunks/dep-d13406fa.js:48018:28)
    at async createServer$2 (/Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vite/dist/node/chunks/dep-d13406fa.js:67848:20)
    at async CAC.<anonymous> (/Users/me/Dev/Projects/Vue/test-vue2/fe/node_modules/vite/dist/node/cli.js:13950:24)
```

**Comment by IndexXuan** [comment]
@mickeyvip Oh, sorry. Fixed it in v0.2.2.
maybe you are in private npm registry(e.g. your company's, you can sync latest version from official npm registry).
see label in this repo README to find latest version info.

**Comment by mickeyvip** [comment]
yes, you are right about the company's registry :)
Thank you!

**Comment by mickeyvip** [comment]
Working good!
Thank you!

**Comment by IndexXuan** [comment]
@mickeyvip Enjoy Viting ！
