### ISSUE TITLE
Error when starting caused by plugins.

### ISSUE THREAD

**Issue by boxsnake** [IndexXuan/vue-cli-plugin-vite#23]
I can not start with `npm run vite`, the console output is like:
```bash
> node ./bin/vite

running: vite --config X:\A\src\node_modules\_vue-cli-plugin-vite@1.0.0-rc.3@vue-cli-plugin-vite\config\index.ts
error when starting dev server:
TypeError: Cannot read property 'apply' of undefined
    at X:\A\src\node_modules\_vite@2.0.5@vite\dist\node\chunks\dep-e0f09032.js:48165:19
    at Array.filter (<anonymous>)
    at resolveConfig (X:\A\src\node_modules\_vite@2.0.5@vite\dist\node\chunks\dep-e0f09032.js:48164:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createServer (X:\A\src\node_modules\_vite@2.0.5@vite\dist\node\chunks\dep-e0f09032.js:68144:20)
    at async CAC.<anonymous> (X:\A\src\node_modules\_vite@2.0.5@vite\dist\node\cli.js:14027:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mjapp@2.5.0 vite: `node ./bin/vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mjapp@2.5.0 vite script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Programs\nodejs\global\cache\_logs\2021-04-19T17_08_49_381Z-debug.log
```

By looking at the ts codes, it is caused by these lines in `node_modules\_vue-cli-plugin-vite@1.0.0-rc.3@vue-cli-plugin-vite\config\index.ts` line 45-48:
```ts
export default defineConfig({
  plugins: [
    envCompatible(),
    // auto infer pages
    htmlTemplate({ pages: vueConfig.pages || {} }),
    vueCli(),
    createVuePlugin(viteOptions.vitePluginVue2Options),
    useMPA
      ? mpa()
      : undefined,
    ...extraPlugins,
  ],
  optimizeDeps: viteOptions.optimizeDeps,
})
```

When this is not mpa, it will add an undefined to `plugins` for user config. Thus, the `flat().filter()` won't deal it properly because it can not access `plugins` for `undefined`.

**Comment by boxsnake** [comment]
As a quick fix, I used `...(useMPA ? mpa() : [])` in my project.

I hope this can be fixed in this plugin.

**Comment by IndexXuan** [comment]
oh you should update this plugin. as of newer(now it is 2.0.5) vite support falsy plugin in plugins as rollup.

**Comment by IndexXuan** [comment]
oh! you already use rc.3. It should vite 2.1.5 inner this plugin. I dont know why ...

**Comment by IndexXuan** [comment]
can you find why you have vite 2.0.5(rc.3 declare 2.1.5 in deps). maybe install yourself? try npm ls vite.

**Comment by boxsnake** [comment]
@IndexXuan yes, I installed vite on my own.

If I use this plugin without vite installed, it says:
```bash
> node ./bin/vite

running: vite --config X:\A\node_modules\_vue-cli-plugin-vite@1.0.0-rc.3@vue-cli-plugin-vite\config\index.ts
'vite' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn vite ENOENT
    at notFoundError (X:\A\node_modules\_cross-spawn@7.0.3@cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (X:\A\node_modules\_cross-spawn@7.0.3@cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (X:\A\node_modules\_cross-spawn@7.0.3@cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (X:\A\node_modules\_cross-spawn@7.0.3@cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn vite',
  path: 'vite',
  spawnargs: [
    '--config',
    'X:\\A\\node_modules\\_vue-cli-plugin-vite@1.0.0-rc.3@vue-cli-plugin-vite\\config\\index.ts'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mjapp@2.5.0 vite: `node ./bin/vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mjapp@2.5.0 vite script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Programs\nodejs\global\cache\_logs\2021-04-20T00_18_39_149Z-debug.log

X:\A>npm ls vite
mjapp@2.5.0 X:\A
+-- UNMET PEER DEPENDENCY vite@2.1.5  -> X:\A\node_modules\_vite@2.1.5@vite extraneous
`-- vue-cli-plugin-vite@1.0.0-rc.3 -> X:\A\node_modules\_vue-cli-plugin-vite@1.0.0-rc.3@vue-cli-plugin-vite
  `-- UNMET PEER DEPENDENCY vite@2.1.5  -> X:\A\node_modules\_vite@2.1.5@vite

npm ERR! peer dep missing: vite@~2.0.0, required by vite-plugin-vue-cli@0.7.1
npm ERR! peer dep missing: vite@~2.0.0, required by vite-plugin-vue-cli@0.7.1
npm ERR! peer dep missing: vite@~2.0.0, required by vite-plugin-vue-cli@0.7.1
npm ERR! peer dep missing: vite@~2.0.0, required by vite-plugin-vue-cli@0.7.1
```

**Comment by boxsnake** [comment]
By using `npm ls vite`, I got:
```bash
+-- UNMET PEER DEPENDENCY vite@2.1.5  -> X:\A\node_modules\_vite@2.1.5@vite extraneous
`-- vue-cli-plugin-vite@1.0.0-rc.3 -> X:\A\node_modules\_vue-cli-plugin-vite@1.0.0-rc.3@vue-cli-plugin-vite
  `-- UNMET PEER DEPENDENCY vite@2.1.5  -> X:\A\node_modules\_vite@2.1.5@vite

npm ERR! peer dep missing: vite@~2.0.0, required by vite-plugin-vue-cli@0.7.1
npm ERR! peer dep missing: vite@~2.0.0, required by vite-plugin-vue-cli@0.7.1
npm ERR! peer dep missing: vite@~2.0.0, required by vite-plugin-vue-cli@0.7.1
npm ERR! peer dep missing: vite@~2.0.0, required by vite-plugin-vue-cli@0.7.1
```

I used vite 2.0.5 because of the peer dep requirements.

**Comment by IndexXuan** [comment]
use 2.1.5. vite command is from vite pkg and deps included by this plugin. no need install yourself. dont know why.

**Comment by IndexXuan** [comment]
maybe in bin/vite use npx vite instead of vite directly? try it

**Comment by boxsnake** [comment]
> maybe in bin/vite use npx vite instead of vite directly? try it

I changed the `vite` to `npx vite` in cross-spawn, and it works. Thanks.
