### ISSUE TITLE
`npm run vite` not work in Windows

### ISSUE THREAD

**Issue by satrong** [IndexXuan/vue-cli-plugin-vite#7]
Error message:
```
> node ./bin/vite

running: vite --config D:\MyFlie\Code\app\node_modules\vue-cli-plugin-vite\config\index.ts
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn vite ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn vite',
  path: 'vite',
  spawnargs: [
    '--config',
    'D:\\MyFlie\\Code\\app\\node_modules\\vue-cli-plugin-vite\\config\\index.ts'
  ]
}
```

After do some below changes is OK:
```js
const params = [
  './node_modules/vite/bin/vite.js',
  `${process.env.BUILD ? 'build' : ''}`,
  process.env.VITE_DEBUG ? '--debug' : '',
  '--config',
  `${configPath}`
].filter(Boolean)

console.log(`running: vite ${params.join(' ')}`)
const serveService = spawn('node', params, { cwd, stdio: 'inherit' })
```

**Comment by IndexXuan** [comment]
@satrong 
It is fixed by https://github.com/IndexXuan/vue-cli-plugin-vite/issues/1
what is your version of vue-cli-plugin-vite, 0.1.3 maybe OK

**Comment by satrong** [comment]
额，我是在你发0.1.3前安装的。现在可以了
